version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
