version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
